# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# https://recommonmark.readthedocs.io/en/latest/index.html#autostructify
# https://recommonmark.readthedocs.io/en/latest/auto_structify.html
# This enables additional features of recommonmark syntax
# import recommonmark
# from recommonmark.transform import AutoStructify

# -- Project information -----------------------------------------------------

project = 'hledger'
author = 'Simon Michael'
copyright = '2019, Simon Michael'
# version = '1.14'
# release = '1.14'


# -- General configuration ---------------------------------------------------

master_doc = 'sitemap'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # https://recommonmark.readthedocs.io
    'recommonmark',
    # https://github.com/ryanfox/sphinx-markdown-tables
    # https://python-markdown.github.io/extensions/tables
    # https://michelf.ca/projects/php-markdown/extra/#table
    'sphinx_markdown_tables',
]

# needs_extensions = {
#     'recommonmark': '1.1',
#     'sphinx_markdown_tables': '2.2',
# }

# http://www.sphinx-doc.org/en/master/usage/markdown.html#configuration
# https://spec.commonmark.org
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
#    '.txt': 'markdown',
}

suppress_warnings = [
    # 'misc.highlighting_failure',
]


# https://stackoverflow.com/questions/16469869/custom-syntax-highlighting-with-sphinx
from pygments.lexer import RegexLexer
from pygments import token
#from pygments.token import *
from sphinx.highlighting import lexers

# silence unknown lexer warnings

for l in [
    'shell',
    'timeclock',
    'timedot',
    'csv',
    'rules',
    'haskell',
    'hledger',
    'example',
  ]:
    class NullLexer(RegexLexer):
        name = l
        tokens = { 'root': [] }
    lexers[l] = lexers['{.'+l+'}'] = NullLexer(startinline=True)

# define custom lexers
# http://pygments.org/docs/lexerdevelopment
# pygmentize -l conf.py:JournalLexer -x
# pygments.highlight(code, lexer, formatter, outfile=None)

class JournalLexer(RegexLexer):
    name = 'journal'
    # aliases = ['hledger']
    # filenames = ['*.journal']

    tokens = {
        'root': [
            (r'(\d\d\d\d[.-/])?\d\d?[.-/]\d\d?', token.Keyword),
            # (r'[a-zA-Z]', token.Name),
            (r'\s', token.Text)
        ]
    }
            # (r' .*\n', Text),
            # (r'\+.*\n', Generic.Inserted),
            # (r'-.*\n', Generic.Deleted),
            # (r'@.*\n', Generic.Subheading),
            # (r'Index.*\n', Generic.Heading),
            # (r'=.*\n', Generic.Heading),
            # (r'.*\n', Text),

lexers['journal'] = lexers['{.journal}'] = JournalLexer(startinline=True)


# https://recommonmark.readthedocs.io/en/latest/index.html#linking-to-headings-in-other-files
# For linking to headings in other files you can use the autosectionlabel sphinx feature, e.g.
#extensions = [
#     # Auto-generate section labels.
#     'sphinx.ext.autosectionlabel',
#]
# # Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# # rather than 'path/to/file:heading'
#autosectionlabel_prefix_document = True
# You would use it like:
#
# <!-- path/to/file_1.md -->
# # Title
# ## My Subtitle
#
# <!-- file_2.md -->
# [My Subtitle][]
# [My Subtitle]: <path/to/file_1:My Subtitle>

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '_site',
    'doc',  # old manuals, for now
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# html_theme_options = {
#     "rightsidebar": "true",
#     "relbarbgcolor": "black"
# }

# https://alabaster.readthedocs.io/en/latest/installation.html
# https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=html_sidebars#options-for-html-output
# Builtin sidebar templates that can be rendered are:
#     localtoc.html – a fine-grained table of contents of the current document
#     globaltoc.html – a coarse-grained table of contents for the whole documentation set, collapsed
#     relations.html – two links to the previous and next documents
#     sourcelink.html – a link to the source of the current document, if enabled in html_show_sourcelink
#     searchbox.html – the “quick search” box
html_sidebars = {
    '**': [
        # 'about.html',
        # 'localtoc.html',
        # 'globaltoc.html',
        'navigation.html',
        'relations.html',
        # 'sourcelink.html',
        'searchbox.html',
        # 'donate.html',
    ]
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add stylesheets to HEAD
html_css_files = [
    # we were using bootstrap 3.3, which was not good on small screens. (Now we use sphinx's theme.)
    # we got it from CDN for speed:
    #'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css',
    # or from same host, to work offline:
    # #$siteRoot$/css/bootstrap.min.css  #  did it need to be an absolute url ?
    #'css/bootstrap.min.css',

    # we're still using some addon styles from the bootswatch "readable" theme.
    'https://maxcdn.bootstrapcdn.com/bootswatch/3.3.0/readable/bootstrap.min.css',

    # and the styles for the highslide image zoomer
    'js/highslide/highslide.css',

    # and our old custom style overides
    'css/style.css',
]

# Add javascript files to HEAD. See also _template/layout.html.
html_js_files = [
    # bootstrap js, I think not used
    # 'js/bootstrap.min.js',
    # highslide image zoomer
    'js/highslide/highslide.js',
    # custom js, currently none
    # 'site.js',
]


html_extra_path = []

# https://recommonmark.readthedocs.io/en/latest/index.html#autostructify
# def setup(app):
#     app.add_config_value('recommonmark_config', {
#             'url_resolver': lambda url: github_doc_root + url,
#             'auto_toc_tree_section': 'Contents',
#             'enable_eval_rst': True,
#             }, True)
    # app.add_transform(AutoStructify)   # IndexError: list index out of range
      # Exception occurred:
      #   File "/usr/local/lib/python3.7/site-packages/docutils/parsers/rst/roles.py", line 356, in math_role
      #     text = rawtext.split('`')[1]
      # IndexError: list index out of range

# AutoStructify comes with the following options:
# enable_auto_toc_tree: enable the Auto Toc Tree feature.
# auto_toc_maxdepth: The max depth of the Auto Toc. Defaults to 1.
# auto_toc_tree_section: when True, Auto Toc Tree will only be enabled on section that matches the title.
# enable_auto_doc_ref: enable the Auto Doc Ref feature. Deprecated
# enable_math: enable the Math Formula feature.
# enable_inline_math: enable the Inline Math feature.
# enable_eval_rst: enable the evaluate embedded reStructuredText feature.
# url_resolver: a function that maps a existing relative position in the document to a http link
# known_url_schemes: a list of url schemes to treat as URLs, schemes not in this list will be assumed to be Sphinx cross-references. Defaults to None, which means treat all URL schemes as URLs. Example: ['http', 'https', 'mailto']

