#!/usr/bin/env bash
# Regenerate the sponsor avatars in src/sponsor.md (between the SPONSOR AVATARS
# markers) from the Open Collective API. Requires curl and jq.
# Run manually (or with "make sponsors") and commit the result.

set -euo pipefail
cd "$(dirname "$0")"

# Show only sponsors who have donated at least this many US dollars in total.
MIN_TOTAL_USD=100

# Open Collective account slugs to exclude regardless of amount
# (the slug is the last part of the account's opencollective.com URL).
EXCLUDE='[
]'

FILE=src/sponsor.md
BEGIN='<!-- SPONSOR AVATARS BEGIN (generated by update-sponsors.sh, do not edit) -->'
END='<!-- SPONSOR AVATARS END -->'

QUERY='{ collective(slug: "hledger") {
  members(role: BACKER, limit: 500) { nodes {
    totalDonations { valueInCents }
    account { name slug type website isIncognito imageUrl(height: 400) }
  } } } }'

html=$(curl -sf https://api.opencollective.com/graphql/v2 \
  -H 'Content-Type: application/json' \
  -d "$(jq -n --arg q "$QUERY" '{query: $q}')" \
| jq -r --argjson mincents $((MIN_TOTAL_USD * 100)) --argjson exclude "$EXCLUDE" '
  (.data.collective.members.nodes
   | map(select(.account != null and .account.slug != null))
   | unique_by(.account.slug)
   | map(select(
       (.account.isIncognito | not)
       and (.account.name != "Guest" and .account.name != "Incognito")
       and (.account.slug | test("^(guest|user)-[0-9a-f]{8}$") | not)
       and .totalDonations.valueInCents >= $mincents
       and (.account.slug as $s | $exclude | index($s) | not)))
   | sort_by(-.totalDonations.valueInCents)) as $all
  | def avatar($height):
      "<a href=\"\((.account.website // "https://opencollective.com/\(.account.slug)") | @html)\" title=\"\(.account.name | @html)\"><img src=\"\(.account.imageUrl | @html)\" alt=\"\(.account.name | @html)\" height=\"\($height)\"></a>";
    ($all | map(select(.account.type == "ORGANIZATION"))[] | avatar(200)),
    "<br>",
    ($all | map(select(.account.type != "ORGANIZATION"))[] | avatar(100))
')

htmlfile=$(mktemp)
trap 'rm -f "$htmlfile"' EXIT
printf '%s\n' "$html" > "$htmlfile"

awk -v begin="$BEGIN" -v end="$END" -v htmlfile="$htmlfile" '
  $0 == begin { print; while ((getline line < htmlfile) > 0) print line; skipping = 1; found = 1; next }
  $0 == end   { skipping = 0 }
  !skipping   { print }
  END { if (!found) { print "error: BEGIN marker not found in file" > "/dev/stderr"; exit 1 } }
' "$FILE" > "$FILE.tmp"
mv "$FILE.tmp" "$FILE"

echo "updated the sponsor avatars in $FILE:"
git diff --stat "$FILE"
